#!/bin/bash

# Directions
# 1) Copy script to a temp location, e.g. /tmp/InstallJenkins.sh
# 2) Make executable, e.g. chmod a+x /tmp/InstallJenkins.sh
# 3) Execute as su, e.g. sudo /tmp/InstallJenkins.sh
